// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220105204508_b")]
    partial class b
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Persistence.Root", b =>
                {
                    b.Property<int>("RootId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOkay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RootId");

                    b.ToTable("Roots");
                });

            modelBuilder.Entity("Persistence.SharedObject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SharedObjects");
                });

            modelBuilder.Entity("Persistence.UniqueProperty", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RootId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RootId");

                    b.ToTable("UniqueProperties");
                });

            modelBuilder.Entity("RootSharedObject", b =>
                {
                    b.Property<int>("RootsRootId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SharedObjectsId")
                        .HasColumnType("TEXT");

                    b.HasKey("RootsRootId", "SharedObjectsId");

                    b.HasIndex("SharedObjectsId");

                    b.ToTable("RootSharedObject");
                });

            modelBuilder.Entity("Persistence.UniqueProperty", b =>
                {
                    b.HasOne("Persistence.Root", null)
                        .WithMany("UniqueProperties")
                        .HasForeignKey("RootId");
                });

            modelBuilder.Entity("RootSharedObject", b =>
                {
                    b.HasOne("Persistence.Root", null)
                        .WithMany()
                        .HasForeignKey("RootsRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.SharedObject", null)
                        .WithMany()
                        .HasForeignKey("SharedObjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence.Root", b =>
                {
                    b.Navigation("UniqueProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
